### ISSUE TITLE
[vite] warning: This assignment will throw because "setLoading" is a constant

### ISSUE THREAD

**Issue by Spectari-code** [brob/astro-hygraph-timeline-example#2]
Hi there, I have been following along with your loading and pagination video on Astro and I'm stuck on the last part. 

Vite seems to not like the fact that I'm changing setLoading as it is a constant, here is the error message in a pastebin, I tried formatting here but it broke up the lines:

https://pastebin.com/hkjkafF7

I'm most likely doing something wrong here, any help would be appreciated, thanks

**Comment by Spectari-code** [comment]
Nevermind I missread

**Comment by brob** [comment]
Glad you got it figured out. Anything in the article that could have helped clarify?
